// generated by `_do_bump_version` script in project root
// Wed 03 Feb 2021 23:57:51 GMT
// DO NOT EDIT

package version

const NAME = "gonic"
const NAME_UPPER = "GONIC"
const NAME_EMBED = "gonicembed"
const VERSION = "v0.12.0"
