// generated by `_do_bump_version` script in project root
// Wed Jan 29 15:34:36 GMT 2020
// DO NOT EDIT

package version

const (
	NAME       = "gonic"
	NAME_UPPER = "GONIC"
	NAME_EMBED = "gonicembed"
	NAME_SCAN  = "gonicscan"
	VERSION    = "v0.6.3"
)
