// generated by `_do_bump_version` script in project root
// Thu 19 Nov 2020 18:48:58 GMT
// DO NOT EDIT

package version

const NAME = "gonic"
const NAME_UPPER = "GONIC"
const NAME_EMBED = "gonicembed"
const VERSION = "v0.11.1"
