run:
  skip-dirs:
    - server/assets
  skip-dirs-use-default: true

linters:
  disable-all: true
  enable:
    - bodyclose
    - depguard
    - dogsled
    - errcheck
    - exportloopref
    - gochecknoglobals
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - goerr113
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - revive
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gochecknoglobals
    - text: "weak cryptographic primitive"
      linters:
        - gosec
    - text: "weak random number generator"
      linters:
        - gosec
    - text: "at least one file in a package should have a package comment"
      linters:
        - stylecheck
