#!/bin/sh

source ./_build_vars
find server/assets/ \
    -type f \
    -exec go run \
        cmd/gonicembed/main.go \
        -out-path server/assets_bytes.go \
        -tag-list embed \
        -package-name server \
        -assets-var-name AssetBytes \
        -asset-path-prefix server/assets/ \
        {} +
go build \
    -o gonic \
    -tags "$(tr '\n' ' ' < _build_tags) embed" \
    cmd/gonic/main.go
