#!/bin/bash

shopt -s globstar

server_base_dir=server
assets_name=assets

resources \
    -declare \
    -var $(sed -E 's/(^|_)([a-z])/\U\2/g' <<< $assets_name) \
    -package ${assets_name}_compiled \
    -output "$server_base_dir/${assets_name}_compiled/${assets_name}_compiled.go" \
    -trim "$server_base_dir/${assets_name}_src/" \
    "$server_base_dir/${assets_name}_src/"**
