// generated by stringer -type Flags cuesheet/cuesheet.go; DO NOT EDIT

package cuesheet

import "fmt"

const flagsName = "NoneDcpFour_chPreScms"

var flagsIndex = [...]uint8{0, 4, 7, 14, 17, 21}

func (i Flags) String() string {
	if i < 0 || i+1 >= Flags(len(flagsIndex)) {
		return fmt.Sprintf("Flags(%d)", i)
	}
	return flagsName[flagsIndex[i]:flagsIndex[i+1]]
}
