name: Lint and test
on:
  push:
    branches:
      - master
      - develop
  pull_request:
jobs:
  test:
    name: Lint and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - name: Install dependencies
        run: |
          sudo apt update -qq
          sudo apt install -y -qq build-essential git sqlite libtag1-dev ffmpeg libasound-dev
      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          skip-go-installation: true
      - name: Test
        run: go test ./...
